### ISSUE TITLE
Error handling seems to be sloppy

### ISSUE THREAD

**Issue by Ersanio** [Ersanio/SNES-Binary-Utility#1]
Despite the program being English, error messages come out as Dutch (my system language) with rather technical jargons no regular user would understand. It's inconsistent and weird.

![i117 cimgpsh_orig](https://user-images.githubusercontent.com/4497840/32869936-e01b36e6-ca79-11e7-9fa1-3f143ee9c9a2.png)

**Comment by bonimy** [comment]
Closing since the project is being filly rewritten.
